import {ISettingTabItem} from '@app/types/setting';

export const DEFAULT_LEAD_TABS: ISettingTabItem[] = [
  {
    key: 'discuss',
    name: 'Thảo luận',
    icon: 'fa-solid fa-comment',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'left', label: 'Cột trái'}],
  },
  {
    key: 'task',
    name: 'Tác vụ',
    icon: 'fa-solid fa-list-check',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'left', label: 'Cột trái'}],
  },
  {
    key: 'attribute',
    name: 'Attribute',
    icon: 'fa-solid fa-address-card',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'left', label: 'Cột trái'}],
  },
  {
    key: 'product',
    name: 'Sản phẩm',
    icon: 'fa-solid fa-cart-arrow-down',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'left', label: 'Cột trái'}],
  },
  {
    key: 'package',
    name: 'Gói dịch vụ',
    icon: 'fa-solid fa-box',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'left', label: 'Cột trái'}],
  },
  {
    key: 'history',
    name: 'Lịch sử',
    icon: 'fa-solid fa-clock-rotate-left',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'right', label: 'Cột phải'}],
  },
  {
    key: 'customer',
    name: 'Khách hàng',
    icon: 'fa-solid fa-user',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [
      {value: 'left', label: 'Cột trái'},
      {value: 'right', label: 'Cột phải'},
    ],
  },
];

export const DEFAULT_TASK_TABS: ISettingTabItem[] = [
  {
    key: 'task',
    name: 'Tác vụ',
    icon: 'fa-solid fa-list-check',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'left', label: 'Cột trái'}],
  },
  {
    key: 'customer',
    name: 'Khách hàng',
    icon: 'fa-solid fa-user',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [
      {value: 'left', label: 'Cột trái'},
      {value: 'right', label: 'Cột phải'},
    ],
  },
  {
    key: 'order',
    name: 'Đơn hàng',
    icon: 'fa-solid fa-file-invoice',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'left', label: 'Cột trái'}],
  },
  {
    key: 'history',
    name: 'Lịch sử',
    icon: 'fa-solid fa-clock-rotate-left',
    active: true,
    positions: ['left'],
    isDefault: true,
    positionOptions: [{value: 'right', label: 'Cột phải'}],
  },
];
